devtools::use_data_raw()
devtools::use_package("stringdist")
devtools::use_package("purrr")
devtools::use_package("magrittr")
devtools::use_package("tibble")
devtools::use_vignette("poc")
devtools::build_vignettes()
library(bookdown)
bookdown::render_book("plop")
devtools::use_test("regex")

